(message "loading erc-config")
(setq erc-email-userid "AriT93")
(setq erc-minibuffer-notice nil)
(setq erc-modules (quote (autoaway autojoin button fill irccontrols match netsplit noncommands pcomplete completion readonly ring scrolltobottom services smiley stamp track unmorse)))
(setq erc-nick "AriT93")
(setq erc-part-reason (quote erc-part-reason-zippy))
(setq erc-prompt-for-password nil)
(setq erc-quit-reason (quote erc-quit-reason-zippy))
(setq erc-show-my-nick t)
(setq erc-track-showcount t)
(setq erc-user-full-name "AriT93")

(provide 'erc-config)