(message "loading keys-config")
(global-set-key [home] 'beginning-of-line)
(global-set-key [end]  'end-of-line)
(global-set-key [C-home] 'beginning-of-buffer)
(global-set-key [C-end] 'end-of-buffer)
(global-set-key [f2] 'senator-jump)
(global-set-key [f8] 'jde-debug)
(global-set-key [S-f5] 'jde-run)
(global-set-key [pause] 'erase-buffer)
(global-set-key [f4] 'goto-line )
(global-set-key [f12] 'write-blog)
(global-set-key [S-f12] 'write-blog-daily)
(global-set-key [f5] 'compile)
(global-set-key (kbd "C-c o") 'occur)
(global-set-key (kbd "M-+") 'text-scale-adjust)
(global-set-key (kbd "M--") 'text-scale-adjust)
(global-set-key (kbd "M-0") 'text-scale-adjust)

(provide 'keys-config)