(message "loading load-path-config")
;;(add-to-list 'load-path (expand-file-name "~/emacs/site/emacs-w3m"))
(add-to-list 'load-path "/usr/local/share/emacs/site-lisp")
;;(add-to-list 'load-path (expand-file-name "~/emacs/site/emacs-w3m/attic"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/color-theme/themes"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/coffee-mode"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/lisp"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/feature-mode"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/other"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/other/css-mode"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/css-mode"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/remember"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/blog"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/html"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/dotnet"))
;;(add-to-list 'load-path (expand-file-name "~/emacs/site/python"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/color-theme"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/java-tools"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/mmm-mode"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/php-mode"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/js2-mode-master"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/ruby"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/auto-complete"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/popup-el"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/yaml-mode"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/ruby-block"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/rinari"))
(add-to-list 'load-path (expand-file-name "~/emacs/site/rdebug"))

(load "ps-print")
;;(load-file "~/emacs/site/cedet/common/cedet.elc")

(autoload 'python-mode "python-mode" "Python editing mode." t)

(provide 'load-path-config)
